config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "dinosaurs#index"

resources :dinosaurs


#get "dinosaurs" => "dinosaurs#index"
#get "dinosaurs/new" => "dinosaurs#new", as: :new_dinosaur
#get "dinosaurs/:id" => "dinosaurs#show", as: :dinosaur

#post "dinosaurs" => "dinosaurs#create"

#get 'dinosaurs/:id/edit' => 'dinosaurs#edit', as: :edit_dinosaur

#patch "dinosaurs/:id" => 'dinosaurs#update'
#delete "dinosaurs/:id" => "dinosaurs#destroy"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  validates :age, length: { maximum: 5 }, allow_blank: true
  validates :image_url, length: { maximum: 255 }, allow_blank: true



  def self.order_by_name
    order(:name)
  end

  #scope :order_by_name, -> {order(:name)}

    def is_baby?
      age < 3
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  def index
    @dinosaurs = Dinosaur.all
  end

  def show
    @dinosaur = Dinosaur.find(params[:id])
  end

  def new
    @dinosaur = Dinosaur.new
  end

  def create
    #dinosaur_params = params.require(:dinosaur).permit(:name, :age, :image_url)
    @dinosaur = Dinosaur.new(dinosaur_params)

    if @dinosaur.save
      redirect_to @dinosaur
    else
      render "new"
    end
  end

  def edit
    @dinosaur = Dinosaur.find(params[:id])
  end

  def update
    @dinosaur = Dinosaur.find(params[:id])
    #dinosaur_params = params.require(:dinosaur).permit(:name, :age, :image_url)

    if @dinosaur.update_attributes(dinosaur_params)
      redirect_to @dinosaur
    else
      render "edit"
    end
  end

private

def dinosaur_params
  params.require(:dinosaur).permit(:name, :age, :image_url)
end

def destroy
  @dinosaur = Dinosaur.find(params[:id])
  @dinosaur.destroy
  redirect_to dinosaurs_path
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/dinosaurs/_form.html.erb
<%= form_for @dinosaur do |f| %>


<ul>
    <% @dinosaur.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>


  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit (@dinosaur.new_record? ? "Create" : "Update") %>

<% end %>

app/views/dinosaurs/edit.html.erb
<h1>Edit Dinosaur</h1>

<%= render "form" %>

app/views/dinosaurs/index.html.erb
<h1>Dinosaurs </h1>

<% @dinosaurs.each do |dinosaur| %>
    <p><%= link_to dinosaur.name, dinosaur_path(dinosaur.id) %></p>


<% end %>

<hr>
<%= link_to "[New Dinosaur]", new_dinosaur_path %>

app/views/dinosaurs/new.html.erb
<h1>New Dinosaur</h1>

<%= render "form" %>

app/views/dinosaurs/show.html.erb
<h1><%= @dinosaur.name %></h1>

<p>Age: <%= @dinosaur.age %></p>
<%= image_tag @dinosaur.image_url %>

<hr>

<%= link_to "[Edit]", edit_dinosaur_path(@dinosaur.id) %>
<%= link_to "[Delete]", dinosaur_path(@dinosaur.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValleysOfDinosaurs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <br></br>
    <hr>

    <%= link_to "[All Dinosaurs]", root_path %>
  </body>
</html>